### ISSUE TITLE
Good first issues

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-camp-europe-19#1]
# Abstract
Qiskit (Terra in particular) has [several bugs tagged as `good first issues`](https://github.com/Qiskit/qiskit-terra/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). These issues are low priority, relatively simple to fix, and they can be a good introduction the Qiskit codebase. This project is about closing as many of those issues as possible.
 
# Members
This project is a fallback to other projects. If you feel that you don't fit in any team, or your project come to a dead end before the hackathon finished, or you just want to improve your python/git/coding skills, then you are welcome here!
 
 - member
 - IBM Coach:
    - @1ucian0 - Slack: `@luciano`
    - @diego-plan9
    - @maddy-tod 

# Deliverable
PRs! Mostly to https://github.com/Qiskit/qiskit-terra/pulls/

**Comment by maddy-tod** [comment]
I'm happy to help out with this too!

**Comment by 1ucian0** [comment]
> I'm happy to help out with this too!

Thanks! Adding you!

**Comment by ruimaranhao** [comment]
I am also happy to help out. 

@danielfobooss: you too?

**Comment by danielfobooss** [comment]
Yes!
