### ISSUE TITLE
Testing visualization modules

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-camp-europe-19#11]
# Abstract
Terra is having troubles testing all the visualization modules (see https://github.com/Qiskit/qiskit-terra/issues/2968). That has [on hold a bunch of issues](https://github.com/Qiskit/qiskit-terra/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22on+hold%22+2968). Probably, the way to go is mocking the external libraries that create this figures and make sure that they are called with the *right* parameters.
 
# Members
Do you have experience testing? Do you breathe `unittest.mock`? Join us!

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - IBM Coach: @1ucian0  - Slack `@luciano`

# Deliverable
A PR closing a lot of bugs!

**Comment by ruimaranhao** [comment]
Cool one. I would be interested.

**Comment by danielfobooss** [comment]
Interested!
