### ISSUE TITLE
Sections for Qiskit textbook

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-camp-europe-19#18]
# Abstract
The Qiskit textbook teaches quantum computing using Qiskit. It is open source, so anyone can add a section.
 
# Description
Topics that would be good to contribute include:
* Kraus operators: what they are and how to use them in noise simulators.
* How to use Qiskit to explore the physics of the devices
* Techniques useful for dealing with connectivity constraints.

# Members

 -
 - IBM Coach: @quantumjim (James Wootton, IBM Research - Zurich)

# Deliverable
A Jupyter notebook or two that will be submitted to the Qiskit textbook.

# GitHub repo
tbd

**Comment by ruimaranhao** [comment]
Count me in for this one.

**Comment by danielfobooss** [comment]
I want in!

**Comment by quantumjim** [comment]
@ruimaranhao @danielfobooss  Great! I won't add you in yet, so that you are free to shop around. But let me know if you'd like to be added.

**Comment by quantumjim** [comment]
If anyone else wants to do a 1 min pitch for this, let me know.

**Comment by quantumjim** [comment]
@ruimaranhao @danielfobooss Have you joined another team? At the moment, this is on course to be closed
