### ISSUE TITLE
Quantagram (Quantum Instagram - diegetic prototype)

### ISSUE THREAD

**Issue by libby-h** [qiskit-community/qiskit-camp-europe-19#19]
# Abstract
We live in an image-obsessed society. The type of images and the networks they occupy influence everything from how we look & see ourselves to geopolitics through rapid news cycles and fake news. As an artist and quantum information theorist, I propose to research, design and build one aspect of a quantum instagram "Quantagram" - a speculative future platform where quantum images can be uploaded and shared. We might consider one of the following questions: How will digital images change once they are encoded using quantum information? What will it mean to share these new quantum images across proprietry quantum networks? And what will the future quantum selfie and face filter look like?
 
While the hackathon will not be enough time to produce a full quantum instagram - as a team we will choose an aspect and produce a (diegetic) prototype

Note - that for me a speculative platform means that while it uses many aspects of qiskit it doesn't need to be fully functional. It's partly a diegetic prototype* intended to raise discussion around certain future and present issues

*https://www.wired.com/2011/02/design-fiction-diegetic-prototypes/

# Members
Needs members

 - @libby-h (github) Slack: `@Libby Heaney` email: libby.heaney@gmail.com; twitter: @libbyheaney (email or twitter best to contact)

 IBM Coach: @quantumjim  

# Deliverable
A diegetic prototype - some functional and some fictional aspects of a future quantagram.

# GitHub repo

**Comment by omarcostahamido** [comment]
https://youtu.be/W-QeGh_qq24?t=123

**Comment by omarcostahamido** [comment]
> _What will it mean to share these new quantum images across proprietary quantum networks?_

I really like this question.

> _And what will the future quantum selfie and face filter look like?_

this should also be very fun to explore. especially if you deconstruct (play around with) the idea of what "a selfie" is/could be in this case.

**Comment by libby-h** [comment]
Hi @omarcostahamido let’s chat! Deconstructing the concept of Selfie in relation to identity/subjectivities could be good. Hopefully catch you tomorrow

**Comment by omarcostahamido** [comment]
Sure, I'm Omar :)
