### ISSUE TITLE
Quantum Artificial Intelligence with Qiskit Aqua

### ISSUE THREAD

**Issue by asierarranz** [qiskit-community/qiskit-camp-europe-19#20]
# Abstract
Develop an app related with artificial intelligence (SVM, qGAN, etc.) using Qiskit Aqua and write an entry-level friendly tutorial. You can check the current tutorials here:
https://github.com/Qiskit/qiskit-iqx-tutorials/tree/master/qiskit/advanced/aqua/artificial_intelligence
Your tutorial could be featured there after the evaluation and follow-up by IBM.

# Members

- @ruimaranhao
-
-
 - IBM Coach: @asierarranz / @maddy-tod  / @ajavadia 

# Deliverable
A Qiskit Tutorial in Jupyter Notebook format 

# GitHub repo

**Comment by asierarranz** [comment]
@ajavadia could be a great coach for this

**Comment by ruimaranhao** [comment]
I would like to join this one.  

I've had the following idea. Implement the algorithm proposed in https://arxiv.org/pdf/1711.02038.pdf.

**Comment by Mircea-Marian** [comment]
I would like to join this one as well.

**Comment by dumkar** [comment]
Other ideas:
https://arxiv.org/abs/1907.02085
https://arxiv.org/abs/1907.05415 (I implemented a very basic example of this in PennyLane already)

**Comment by ajavadia** [comment]
> @ajavadia could be a great coach for this

Thanks but I feel like I'm not the best person for this! @stefan-woerner or others might be able to help.

**Comment by Mircea-Marian** [comment]
Quantum Genetic Algorithms would be a great topic as well:
https://www.sciencedirect.com/science/article/abs/pii/S2210650216303807

**Comment by iturtle100** [comment]
Quantum Perceptron: https://www.nature.com/articles/s41534-019-0140-4.pdf

**Comment by shaojunsun** [comment]
Could you add me to this group? Thank you

**Comment by alexzwang** [comment]
Can you add me to the project?
