### ISSUE TITLE
Quantum Circuit (Formal) Verification 

### ISSUE THREAD

**Issue by kerenavnery** [qiskit-community/qiskit-camp-europe-19#22]
# Abstract

Formal Verification is used in hardware design to make sure a design is doing what it is supposed to do. (https://en.wikipedia.org/wiki/Functional_verification)
How to do a quantum computation:
1. Design your circuit
2. Code the circuit
**3. Make sure there are no errors in the code and the functionality is implemented as designed**
4. Send to a backend and profit!
 
# Description 
Verification is mainly to make sure the **design is implemented correctly by the user.** It is not about errors included in the hardware or gates.

# Members
 - @kerenavnery - Slack: `@kerena` email: keren.avnery@weizmann.ac.il

 - IBM Coach: @githubhandle 

# Repository
https://github.com/kerenavnery/qiskit-terra

**Comment by 1ucian0** [comment]
I would like to hear more about this!
