### ISSUE TITLE
Quantum Stories

### ISSUE THREAD

**Issue by pdyxs** [qiskit-community/qiskit-camp-europe-19#24]
# Abstract

Use interactive storytelling as a format for explaining and teaching quantum programming, using hidden opinions as an analog for quantum bits.
 
# Description

We’ve all had stories with quantum properties: stories where our opinion on a topic was uncertain (superposition), where those opinions were solidified by being questioned (measurement), and where our opinions were wrapped up in someone else’s (entanglement). We’ve all had stories where events (gates) have changed our opinions, and where those changes are contingent on our opinions of others (controlled gates).

Stories are also how we relate to the world, our basic building block of understanding. Our thoughts and opinions share many of the properties and complexities of quantum states. By framing the complexities of quantum circuits inside human stories, and letting people play with those circuits/stories, we can help them gain a rich understanding of the basic operations of quantum computers.

In this project, we’d write one or more quantum stories, work out how those stories change with the circuits that drive them, and turn them into interactive toys to allow non-quantum-literate users to gain an understanding of the quantum computing world. If there’s time, we could even allow users to run their stories on the IBM quantum computers, to see how they change when we introduce the chaos of real life/quantum errors.

# Members
 - ... (potentially @pdyxs)
 - IBM Coach: 

# Deliverable
An interactive toy/explorable (ideally web-based) for one or more stories

# GitHub repo

**Comment by quantumjim** [comment]
I'd be happy to coach.
