### ISSUE TITLE
A Responsive Quantum Circuit Builder

### ISSUE THREAD

**Issue by pdyxs** [qiskit-community/qiskit-camp-europe-19#25]
# Abstract
A circuit builder that provides real-time feedback to developers about how their actions change the states of the bits.
 
# Description
One of the fundamental problems in quantum programming is that the maths is, quite simply, impossible for a human mind. Unlike in classical computing, it quickly becomes unfeasible to think through the potential results of a simple calculation or workflow.

In order to deal with this, we need tools that allow circuits to be built quickly and interactively, giving developers real-time feedback on the internal states of their qbits across the circuit as they build them. This would be an invaluable tool for both the teaching of quantum programming and the practice of it.

This project would involve the development of such a tool*. It would require designing simple visual representations of internal quantum states that are represented across the circuits, and then linking these tools with the qiskit libraries and IBM Quantum computers.

*I’ve previously built a tool that does this for non-complex quantum states in Unity (webgl version at http://qbyte.surge.sh). This project would involve re-tooling this (and likely rebuilding it) using the qiskit libraries and designing the complex state representations.

# Members
... (potentially @pdyxs)
 - IBM Coach: 

# Deliverable
An interactive tool for developers, integrated with qiskit

# GitHub repo

**Comment by Galvien** [comment]
(a msg from @kerenavnery):
We can combine this issue with #22
