### ISSUE TITLE
Quantum Minesweeper

### ISSUE THREAD

**Issue by mrossinek** [qiskit-community/qiskit-camp-europe-19#28]
# Abstract
This is probably very similar to the previously suggested Quantum Educational Games but a little more specific. The classic minesweeper game is suited very well for a quantum-based port. One idea of an implementation would be to have several classical boards in a superposition with each other and provide a set of different measurement options to the user. [See also here](http://www.cass-hpc.com/solutions/scientific-education/quantum-minesweeper/)
 
# Description 

As described at the link above, an implementation of this game has existed before. However, the Android app mentioned there is nowhere to be found. A [Flash-based application](http://qgames.gorengordon.com/QuantumMinesweeper/qMinesweeper.html) does exist at the homepage of one of the authors (though I did not give it a try yet).
Besides the above mentioned idea of several classical boards in a superposition with one another different design are possible for this kind of game and I am happy to discuss these.
Another notable mention is this game: [Quantum Catsweeper](http://qgames.gorengordon.com/QuantumMinesweeper/qMinesweeper.html)

# Members

 - @githubhandle 
 - IBM Coach: @githubhandle 

# Deliverable

A prototype implementation of Quantum Minesweeper.

# GitHub repo

TBD

**Comment by asierarranz** [comment]
I like this idea a lot!

**Comment by mrossinek** [comment]
Closing this as an orphaned project due to lack of interest. If anybody still wants to work on this you will have to form a team with a new team leader. In case you want some more information or discuss a little you can find me at #39.
