### ISSUE TITLE
Circuit rewriting in new basis [merged with #27]

### ISSUE THREAD

**Issue by ajavadia** [qiskit-community/qiskit-camp-europe-19#29]
# Abstract
This is a compiler project.

The current Qiskit gate hierarchy starts with `u3` and `cx` gates at the bottom (which can do universal computation), and builds other gates on top of them (`cz`, `swap`, `cx`, etc.). As a result, gates always get decomposed down in this hierarchy (according to their `definition`), and it is not possible to decompose across or into other basis gates (say rewrite the circuit in the `u3`+`cz` basis).

The proposal is to allow multiple `decomposition` rules per gate, and have the transpiler make intelligent decisions on which rule to choose to expand a gate, based on the context. The user must be able to easily add new rules, or to force a rule to be used during transpilation.

I would probably be working on this in my free time at the hackathon anyway, but other enthusiasts are also welcome!

 
# Description 

# Members

 - 
 - IBM Coach: @ajavadia  

# Deliverable
A Terra pull request

# GitHub repo

**Comment by cicacica** [comment]
This sounds interesting. I solved a similar problem, but the complexity was something like exp. Do you have references regarding the decomposition rules?

**Comment by fmozafari** [comment]
I'm interested to this project. Can you add me, please?
