### ISSUE TITLE
Improved Hamiltonian simulation

### ISSUE THREAD

**Issue by anedumla** [qiskit-community/qiskit-camp-europe-19#36]
# Abstract
Implement the technique for Hamiltonian simulation suggested in this paper: https://arxiv.org/pdf/1907.11679.pdf

# Members

 - IBM Coach: @anedumla 

# Deliverable
Aqua implementation and Jupyter notebook.

# GitHub repo
tbd

**Comment by bourreauEric** [comment]
May be, I can be interested
