### ISSUE TITLE
Hamiltonian and Lindblad classes for Aer OpenPulse simulator

### ISSUE THREAD

**Issue by chriseclectic** [qiskit-community/qiskit-camp-europe-19#6]
# Abstract

Add Python classes and functions for building a system Hamiltonian and Lindblad dissipators for the upcoming OpenPulse simulator backend for Qiskit Aer.
 
# Description 

An OpenPulse simulator backend will soon be added to Qiskit Aer ([PR 263](https://github.com/Qiskit/qiskit-aer/pull/263)). Currently the interface for this simulator uses the OpenPulse backend specification JSON for constructing a Hamiltonian.

This project would be to:
* Write Python classes for building a system Hamiltonian for pulse simulation
* Write Python classes for building a system Lindblad dissipator for noisy pulse simulation
* Write converter that can serialize/deserialize these objects to and from the open pulse specification json.
* Add helper functions for constructing these Hamiltonian objects for IBMQ backends from backend properties.

# Members

- @iturtle100
- IBM Coach: @chriseclectic / @eggerdj 

# Deliverable

Aer module

# GitHub repo

[qiskit-aer](https://github.com/Qiskit/qiskit-aer)

**Comment by eggerdj** [comment]
@chriseclectic I'm also interested in this one. Can we co-coach it?
