### ISSUE TITLE
Stabilizer, Clifford, Pauli classes for terra.quantum_info

### ISSUE THREAD

**Issue by chriseclectic** [qiskit-community/qiskit-camp-europe-19#7]
# Abstract

 
Write `Pauli` and `Clifford` operator classes, and `Stabilizer` quantum state classes for `quantum_info` module.

# Description 

An operator class and quantum state class framework was recently introduced into the qiskit-terra quantum_info module which currently includes matrix operators (`Operator`) quantum channel operators (`SuperOp`, `Kraus`, `Choi` etc), and quantum state classes (`Statevector` and `DensityMatrix`). For use in many quantum information applications it would be good to add optimized classes for `Pauli`, `Clifford` operators and `Stabilizer` states using this framework.

Currently code exists for Pauli operators and partial code exists for Clifford operators in qiskit-ignis, but these need updating to use the operator framework.

These classes could be used for applications to Aqua (eg VQE), Terra (transpiler passes), Ignis (Randomized benchmarking, randomized compiling, etc), and quantum error correction.

An extended goal would be to use these to implement a new transpiler pass or ignis application using classes (eg clifford sysnthesis or randomized compiling)

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - IBM Coach: @chriseclectic

# Deliverable

Extend terra quantum_info module.
Possibly transpiler pass or ignis module

# GitHub repo

TBD

**Comment by we-taper** [comment]
Anyone interested in this?
