### ISSUE TITLE
Tensor network simulation methods for Aer qasm simulator

### ISSUE THREAD

**Issue by chriseclectic** [qiskit-community/qiskit-camp-europe-19#8]
# Abstract

 
New qasm simulator method based on a tensor network state ansatz.

# Description 

Classical simulations for quantum systems is inefficient due to the exponential memory requirement of storing the statevector. Tensor network methods have been used in condensed matter for large scale simulations by using an approximate compressed representation of a tensor network state which have efficient methods for updating them. Qiskit Aer includes a matrix product state simulation methods but other tensor network states exist that could be added included, for example:

- Matrix product density operators (MPDO) for density matrix simulations
- Projected entangled pair states (PEPS) for statevector simulations.

The goal of this project would be to pick one of these states and implement it as a new simulation method for the qasm simulator in Qiskit Aer, and benchmark for what kinds of circuits / applications / noise models it has better performance than the current simulation methods.

This project would require knowledge of tensor network algorithms and their implementation in C++

# Members

 - Philippe Suchsland
 - IBM Coach: @chriseclectic

# Deliverable

Qiskit Aer `State` subclass that can be used with the `QasmSimulator`

# GitHub repo

 TBD

**Comment by dumkar** [comment]
Interested but not enough tensor network & C++ knowledge I'm afraid.
